export const size = {
  tiny: 8,
  small: 12,
  normal: 14,
  large: 18,
  largeX: 20,
  h1: 40,
  h2: 34,
  h3: 28,
  h4: 22,
  h5: 16,
  h6: 10,
  h7: 4,
};

export const fontFamily = {
  GilroyMedium: 'Gilroy-Medium',
  GilroyLight: 'Gilroy-Light',
  GilroyExtraBold: 'Gilroy-ExtraBold',
  GilroySemiBold: 'Gilroy-SemiBold',
  Quicksand: 'Quicksand',
  QuicksandBold: 'Quicksand-Bold',
  QuicksandMedium: 'Quicksand-Medium',
  QuicksandSemiBold: 'Quicksand-SemiBold',
  CabinBold: 'Cabin-Bold',
  CabinRegular: 'Cabin-Regular',
  CabinSemiBold: 'Cabin-SemiBold',
  Cabin: 'Cabin',
  ComfortaaBold: 'Comfortaa-Bold',
  ComfortaaMedium: 'Comfortaa-Medium',
  Comfortaa: 'Comfortaa',
  FiraSansExtraLight: 'FiraSans-ExtraLight',
  FiraSansMedium: 'FiraSansMedium',
  RobotoBold: 'Roboto-Bold',
  RobotoLight: 'Roboto-Light',
  RobotoMedium: 'Roboto-Medium',
  SourceSansProLight: 'SourceSansPro-Light',
  SourceSansProRegular: 'SourceSansProRegular',
  SourceSansProSemiBold: 'SourceSansProSemiBold',
};
